# Generated by Django 5.2.3 on 2025-06-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_meeting_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='email',
            field=models.EmailField(default='user123@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
